select * from customer limit 20;
select column_name
FROM information_schema.columns
WHERE table_name = 'customer';
--q1 what is total revenue generated by male vs female customer
select gender,sum(purchase_amount)as revenue
from customer
group by gender;
--q2 which are the top 5 product with the highest winning rate
select item_purchased,avg(review_rating)as "avereage product rating"
from customer 
group by item_purchased
order by avg(review_rating)desc
limit 5;
--q3 compare  the average purchase amount between standard and express shipping

SELECT shipping_type,
       ROUND(AVG(purchase_amount), 2) AS average_purchase_amount
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;
--q4 do subscribed customer spend more? compare average spend and total revenue between subscribed and non subscribers
select subscription_status,
count(customer_id)as total_customers,
round(avg(purchase_amount),2)as avg_spend,
round(avg(purchase_amount ),2)as total_revenue
from customer
group by subscription_status
order by total_revenue,avg_spend desc;

--q5 which 5 product have the highest percentage of purchase with discount applied?
select item_purchased,
round(100*sum(case when discount_applied ='Yes' THEN 1 else 0 End)/count(*),2)as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
--q6 what are the top 3 most purchased product in each category?
WITH item_counts AS (
    SELECT
        Category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
		 ROW_NUMBER() OVER (PARTITION BY Category ORDER BY count (customer_id) DESC) AS item_rank
    FROM customer
    GROUP BY  Category, item_Purchased
)
select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3
--q7 Are customer who are buyers (more then 5 previous purchase)also likely to  subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases >5
group by  subscription_status
--q8 what is the revenue contribution of each age group?
select age_group,
sum(purchase_amount)as total_revenue
from customer
group by age_group
order by total_revenue desc;